import { Inter } from 'next/font/google'
import 'styles/index.css'

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter'
})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    // Chrome extensions mess with classnames and attributes, disable warnings
    return <html className={inter.variable} lang='en' translate='no' suppressHydrationWarning>
        <body suppressHydrationWarning>
            {children}
        </body>
    </html>
}
